name: Recovery Building

on: [push]

env:
  DEVICE: star2qltechn-fox-9.0
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x $DEVICE/initial.sh
              . $DEVICE/initial.sh
              
       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.TOKEN }}

         run: |
               chmod +x $DEVICE/build.sh
               . $DEVICE/build.sh
